site_name: VSE EasyCal v2.3 Documentation
site_url: ""
use_directory_urls: false
nav:
    - Home: index.md
    - Basics: basics.md
    - Setup: program.md
    - Calibration: procedure.md
    - Cal.flow: calflow.md
    - Advanced: advanced.md
    - FAQ: faqs.md
    - About: about.md
theme:
    name: material
    nav_style: dark
    locale: en
    logo: img/logo.png
    code_wrap: true
    features:
      - navigation.tabs
      - toc.integrate
      - navigation.expand
      - navigation.top
      - navigation.footer
      - content.tooltips
      - content.tabs.link
      - search.highlight
    palette:
      scheme: slate
      primary: red
      accent: red
#    hide:
#      - toc
plugins: 
  - offline
  - search:
        lang: en
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          site_name: "VSE EasyCal v2.3 Dokumentation"
          build: true
#          admonition_translations:
#            - tip: Tipp
#            - warning: Warnung
#            - note: Notiz
#            - danger: Gefahr
#            - important: Wichtig
          nav_translations:
            Home: Start
            Basics: Erste Schritte
            Setup: Vorbereitung
            Calibration: Kalibrierung
            Cal.flow: Cal.flow
            Advanced: Sonderfunktionen
            About: Über
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
        permalink: "#"
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de